/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as QrcodeImport } from './routes/qrcode'
import { Route as ProjImport } from './routes/proj'
import { Route as CvImport } from './routes/cv'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const SymbolsLazyImport = createFileRoute('/symbols')()
const ScreenLazyImport = createFileRoute('/screen')()
const GradientWallpaperLazyImport = createFileRoute('/gradient-wallpaper')()
const DvdLogoLazyImport = createFileRoute('/dvd-logo')()
const BusinessCardLazyImport = createFileRoute('/business-card')()

// Create/Update Routes

const SymbolsLazyRoute = SymbolsLazyImport.update({
  path: '/symbols',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/symbols.lazy').then((d) => d.Route))

const ScreenLazyRoute = ScreenLazyImport.update({
  path: '/screen',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/screen.lazy').then((d) => d.Route))

const GradientWallpaperLazyRoute = GradientWallpaperLazyImport.update({
  path: '/gradient-wallpaper',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/gradient-wallpaper.lazy').then((d) => d.Route),
)

const DvdLogoLazyRoute = DvdLogoLazyImport.update({
  path: '/dvd-logo',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/dvd-logo.lazy').then((d) => d.Route))

const BusinessCardLazyRoute = BusinessCardLazyImport.update({
  path: '/business-card',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/business-card.lazy').then((d) => d.Route))

const QrcodeRoute = QrcodeImport.update({
  path: '/qrcode',
  getParentRoute: () => rootRoute,
} as any)

const ProjRoute = ProjImport.update({
  path: '/proj',
  getParentRoute: () => rootRoute,
} as any)

const CvRoute = CvImport.update({
  path: '/cv',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvImport
      parentRoute: typeof rootRoute
    }
    '/proj': {
      id: '/proj'
      path: '/proj'
      fullPath: '/proj'
      preLoaderRoute: typeof ProjImport
      parentRoute: typeof rootRoute
    }
    '/qrcode': {
      id: '/qrcode'
      path: '/qrcode'
      fullPath: '/qrcode'
      preLoaderRoute: typeof QrcodeImport
      parentRoute: typeof rootRoute
    }
    '/business-card': {
      id: '/business-card'
      path: '/business-card'
      fullPath: '/business-card'
      preLoaderRoute: typeof BusinessCardLazyImport
      parentRoute: typeof rootRoute
    }
    '/dvd-logo': {
      id: '/dvd-logo'
      path: '/dvd-logo'
      fullPath: '/dvd-logo'
      preLoaderRoute: typeof DvdLogoLazyImport
      parentRoute: typeof rootRoute
    }
    '/gradient-wallpaper': {
      id: '/gradient-wallpaper'
      path: '/gradient-wallpaper'
      fullPath: '/gradient-wallpaper'
      preLoaderRoute: typeof GradientWallpaperLazyImport
      parentRoute: typeof rootRoute
    }
    '/screen': {
      id: '/screen'
      path: '/screen'
      fullPath: '/screen'
      preLoaderRoute: typeof ScreenLazyImport
      parentRoute: typeof rootRoute
    }
    '/symbols': {
      id: '/symbols'
      path: '/symbols'
      fullPath: '/symbols'
      preLoaderRoute: typeof SymbolsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CvRoute,
  ProjRoute,
  QrcodeRoute,
  BusinessCardLazyRoute,
  DvdLogoLazyRoute,
  GradientWallpaperLazyRoute,
  ScreenLazyRoute,
  SymbolsLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cv",
        "/proj",
        "/qrcode",
        "/business-card",
        "/dvd-logo",
        "/gradient-wallpaper",
        "/screen",
        "/symbols"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cv": {
      "filePath": "cv.tsx"
    },
    "/proj": {
      "filePath": "proj.tsx"
    },
    "/qrcode": {
      "filePath": "qrcode.tsx"
    },
    "/business-card": {
      "filePath": "business-card.lazy.tsx"
    },
    "/dvd-logo": {
      "filePath": "dvd-logo.lazy.tsx"
    },
    "/gradient-wallpaper": {
      "filePath": "gradient-wallpaper.lazy.tsx"
    },
    "/screen": {
      "filePath": "screen.lazy.tsx"
    },
    "/symbols": {
      "filePath": "symbols.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
