/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SymbolsImport } from './routes/symbols'
import { Route as ScreenImport } from './routes/screen'
import { Route as QrcodeImport } from './routes/qrcode'
import { Route as ProjImport } from './routes/proj'
import { Route as MidiParserImport } from './routes/midi-parser'
import { Route as GradientWallpaperImport } from './routes/gradient-wallpaper'
import { Route as DvdLogoImport } from './routes/dvd-logo'
import { Route as CvImport } from './routes/cv'
import { Route as BusinessCardImport } from './routes/business-card'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SymbolsRoute = SymbolsImport.update({
  path: '/symbols',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/symbols.lazy').then((d) => d.Route))

const ScreenRoute = ScreenImport.update({
  path: '/screen',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/screen.lazy').then((d) => d.Route))

const QrcodeRoute = QrcodeImport.update({
  path: '/qrcode',
  getParentRoute: () => rootRoute,
} as any)

const ProjRoute = ProjImport.update({
  path: '/proj',
  getParentRoute: () => rootRoute,
} as any)

const MidiParserRoute = MidiParserImport.update({
  path: '/midi-parser',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/midi-parser.lazy').then((d) => d.Route))

const GradientWallpaperRoute = GradientWallpaperImport.update({
  path: '/gradient-wallpaper',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/gradient-wallpaper.lazy').then((d) => d.Route),
)

const DvdLogoRoute = DvdLogoImport.update({
  path: '/dvd-logo',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/dvd-logo.lazy').then((d) => d.Route))

const CvRoute = CvImport.update({
  path: '/cv',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cv.lazy').then((d) => d.Route))

const BusinessCardRoute = BusinessCardImport.update({
  path: '/business-card',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/business-card.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/business-card': {
      id: '/business-card'
      path: '/business-card'
      fullPath: '/business-card'
      preLoaderRoute: typeof BusinessCardImport
      parentRoute: typeof rootRoute
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvImport
      parentRoute: typeof rootRoute
    }
    '/dvd-logo': {
      id: '/dvd-logo'
      path: '/dvd-logo'
      fullPath: '/dvd-logo'
      preLoaderRoute: typeof DvdLogoImport
      parentRoute: typeof rootRoute
    }
    '/gradient-wallpaper': {
      id: '/gradient-wallpaper'
      path: '/gradient-wallpaper'
      fullPath: '/gradient-wallpaper'
      preLoaderRoute: typeof GradientWallpaperImport
      parentRoute: typeof rootRoute
    }
    '/midi-parser': {
      id: '/midi-parser'
      path: '/midi-parser'
      fullPath: '/midi-parser'
      preLoaderRoute: typeof MidiParserImport
      parentRoute: typeof rootRoute
    }
    '/proj': {
      id: '/proj'
      path: '/proj'
      fullPath: '/proj'
      preLoaderRoute: typeof ProjImport
      parentRoute: typeof rootRoute
    }
    '/qrcode': {
      id: '/qrcode'
      path: '/qrcode'
      fullPath: '/qrcode'
      preLoaderRoute: typeof QrcodeImport
      parentRoute: typeof rootRoute
    }
    '/screen': {
      id: '/screen'
      path: '/screen'
      fullPath: '/screen'
      preLoaderRoute: typeof ScreenImport
      parentRoute: typeof rootRoute
    }
    '/symbols': {
      id: '/symbols'
      path: '/symbols'
      fullPath: '/symbols'
      preLoaderRoute: typeof SymbolsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  BusinessCardRoute,
  CvRoute,
  DvdLogoRoute,
  GradientWallpaperRoute,
  MidiParserRoute,
  ProjRoute,
  QrcodeRoute,
  ScreenRoute,
  SymbolsRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/business-card",
        "/cv",
        "/dvd-logo",
        "/gradient-wallpaper",
        "/midi-parser",
        "/proj",
        "/qrcode",
        "/screen",
        "/symbols"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/business-card": {
      "filePath": "business-card.tsx"
    },
    "/cv": {
      "filePath": "cv.tsx"
    },
    "/dvd-logo": {
      "filePath": "dvd-logo.tsx"
    },
    "/gradient-wallpaper": {
      "filePath": "gradient-wallpaper.tsx"
    },
    "/midi-parser": {
      "filePath": "midi-parser.tsx"
    },
    "/proj": {
      "filePath": "proj.tsx"
    },
    "/qrcode": {
      "filePath": "qrcode.tsx"
    },
    "/screen": {
      "filePath": "screen.tsx"
    },
    "/symbols": {
      "filePath": "symbols.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
